import {
  LocalPizza,
  Fastfood,
  LunchDining,
  Restaurant,
  LocalDrink,
  Cake,
  SetMeal,
  Icecream,
  EmojiFoodBeverage,
  BakeryDining,
  Tapas,
  RamenDining,
  LocalCafe,
  SportsBar,
  WineBar,
} from "@mui/icons-material";

export const AVAILABLE_ICONS: Record<string, JSX.Element> = {
  LocalPizza: <LocalPizza fontSize="large" />,
  Fastfood: <Fastfood fontSize="large" />,
  LunchDining: <LunchDining fontSize="large" />,
  Restaurant: <Restaurant fontSize="large" />,
  LocalDrink: <LocalDrink fontSize="large" />,
  Cake: <Cake fontSize="large" />,
  SetMeal: <SetMeal fontSize="large" />,
  Icecream: <Icecream fontSize="large" />,
  EmojiFoodBeverage: <EmojiFoodBeverage fontSize="large" />,
  BakeryDining: <BakeryDining fontSize="large" />,
  Tapas: <Tapas fontSize="large" />,
  RamenDining: <RamenDining fontSize="large" />,
  LocalCafe: <LocalCafe fontSize="large" />,
  SportsBar: <SportsBar fontSize="large" />,
  WineBar: <WineBar fontSize="large" />,
};
